services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  app:
    build:
      context: .
    image: "pablo4p/bookstore-api:latest"
    container_name: app
    depends_on:
     - db
     - redis
    environment:
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    ports:
      - "8080:8080"
