CREATE TABLE books (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(500) NOT NULL,
    author VARCHAR(128) NOT NULL,
    main_genre VARCHAR(48) NOT NULL,
    sub_genre VARCHAR(48) NOT NULL,
    type VARCHAR(48) NOT NULL,
    price DECIMAL, -- Usado DECIMAL ao invés de DOUBLE para valores monetários
    rating DECIMAL, -- Usado DECIMAL ao invés de DOUBLE para valores de avaliação
    number_of_people_rated INTEGER,
    url VARCHAR(2048) NOT NULL
);
